import { expect } from "chai";
import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

// Real Groth16 proofs generated by circuits/scripts/prove_fixture.js for one
// seeded, self-consistent credential. Using real proofs here (rather than
// all-zero placeholder calldata) is the whole point of M1: it proves the
// compiled verifiers, the Poseidon commitment layout, and the gateway's
// wiring are actually consistent with each other, not just individually
// plausible.
const FIXTURES_PATH = path.join(__dirname, "..", "..", "circuits", "fixtures", "fixtures.json");
const fixtures = JSON.parse(fs.readFileSync(FIXTURES_PATH, "utf8"));

function fieldToBytes32(decimalString: string): string {
  return "0x" + BigInt(decimalString).toString(16).padStart(64, "0");
}

describe("VerificationGateway", function () {
  let registry: any;
  let anchor: any;
  let revocation: any;
  let gateway: any;
  let claimVerifier: any;
  let nonRevocationVerifier: any;
  let issuerMembershipVerifier: any;
  let owner: any;
  let addr1: any;
  let addr2: any;

  const credentialHash = ethers.id("cred1");
  // pubSignals = [isValid, credentialRoot, threshold]
  const anchoredPoseidonCommitment = fieldToBytes32(fixtures.claimProver.publicSignals[1]);

  beforeEach(async function () {
    [owner, addr1, addr2] = await ethers.getSigners();

    const IssuerRegistry = await ethers.getContractFactory("IssuerRegistry");
    registry = await IssuerRegistry.deploy(owner.address);

    const CredentialAnchor = await ethers.getContractFactory("CredentialAnchor");
    anchor = await CredentialAnchor.deploy(await registry.getAddress());

    const RevocationRegistry = await ethers.getContractFactory("RevocationRegistry");
    revocation = await RevocationRegistry.deploy(await registry.getAddress(), await anchor.getAddress());

    const ClaimProverVerifier = await ethers.getContractFactory("ClaimProverVerifier");
    claimVerifier = await ClaimProverVerifier.deploy();

    const NonRevocationVerifier = await ethers.getContractFactory("NonRevocationVerifier");
    nonRevocationVerifier = await NonRevocationVerifier.deploy();

    const IssuerMembershipVerifier = await ethers.getContractFactory("IssuerMembershipVerifier");
    issuerMembershipVerifier = await IssuerMembershipVerifier.deploy();

    const VerificationGateway = await ethers.getContractFactory("VerificationGateway");
    gateway = await VerificationGateway.deploy(
      await claimVerifier.getAddress(),
      await nonRevocationVerifier.getAddress(),
      await revocation.getAddress(),
      await anchor.getAddress()
    );

    await registry.registerIssuer("did:ethr:123", owner.address, "QmHash");
    // Anchor a credential whose poseidonCommitment matches the fixture's
    // credentialRoot, so proofs generated against that root are actually
    // checkable against something on-chain.
    await anchor.anchorCredential(credentialHash, anchoredPoseidonCommitment, "did:ethr:123", ethers.ZeroHash);
  });

  describe("verifyClaimProof", function () {
    it("accepts a real ClaimProver proof for an anchored, non-revoked credential", async function () {
      const { pA, pB, pC, pubSignals } = fixtures.claimProver.solidityCalldata;
      const result = await gateway.verifyClaimProof.staticCall(credentialHash, pA, pB, pC, pubSignals);
      expect(result).to.be.true;

      const tx = await gateway.verifyClaimProof(credentialHash, pA, pB, pC, pubSignals);
      await expect(tx).to.emit(gateway, "VerificationSuccessful").withArgs(credentialHash, owner.address, "ClaimProver");
    });

    it("rejects a proof whose public credentialRoot does not match the on-chain anchor", async function () {
      const { pA, pB, pC, pubSignals } = fixtures.claimProver.solidityCalldata;
      const tamperedHash = ethers.id("cred-not-anchored-with-this-root");
      await anchor.anchorCredential(tamperedHash, ethers.id("some-other-commitment"), "did:ethr:123", ethers.ZeroHash);

      const result = await gateway.verifyClaimProof.staticCall(tamperedHash, pA, pB, pC, pubSignals);
      expect(result).to.be.false;
    });

    it("fails if credential is revoked", async function () {
      await revocation.setIssuerSigners("did:ethr:123", [owner.address, addr1.address, addr2.address]);

      await revocation.proposeRevocation(credentialHash, "did:ethr:123");
      await revocation.connect(addr1).approveRevocation(credentialHash, "did:ethr:123", 1, "Testing");

      const { pA, pB, pC, pubSignals } = fixtures.claimProver.solidityCalldata;
      const result = await gateway.verifyClaimProof.staticCall(credentialHash, pA, pB, pC, pubSignals);
      expect(result).to.be.false;
    });

    it("fails for a malformed / all-zero proof", async function () {
      const pA: any = [0, 0];
      const pB: any = [[0, 0], [0, 0]];
      const pC: any = [0, 0];
      const pubSignals: any = [0, 0, 0];

      const result = await gateway.verifyClaimProof.staticCall(credentialHash, pA, pB, pC, pubSignals);
      expect(result).to.be.false;
    });
  });

  describe("verifyNonRevocationProof", function () {
    it("accepts a real NonRevocation proof once its root is published", async function () {
      const { pA, pB, pC, pubSignals } = fixtures.nonRevocation.solidityCalldata;
      // pubSignals = [isValid, credentialRoot, revocationTreeRoot]
      await gateway.updateRevocationTreeRoot(pubSignals[2]);

      const result = await gateway.verifyNonRevocationProof.staticCall(credentialHash, pA, pB, pC, pubSignals);
      expect(result).to.be.true;
    });

    it("rejects a NonRevocation proof against a stale root", async function () {
      const { pA, pB, pC, pubSignals } = fixtures.nonRevocation.solidityCalldata;
      // Never published -> revocationTreeRoot defaults to 0, which won't match.
      const result = await gateway.verifyNonRevocationProof.staticCall(credentialHash, pA, pB, pC, pubSignals);
      expect(result).to.be.false;
    });

    it("only the root publisher may update the revocation tree root", async function () {
      const { pubSignals } = fixtures.nonRevocation.solidityCalldata;
      await expect(gateway.connect(addr1).updateRevocationTreeRoot(pubSignals[2])).to.be.revertedWith(
        "Not authorized to publish revocation root"
      );
    });
  });

  describe("IssuerMembershipVerifier (standalone)", function () {
    it("verifies a real issuer-membership proof", async function () {
      const { pA, pB, pC, pubSignals } = fixtures.issuerMembership.solidityCalldata;
      const result = await issuerMembershipVerifier.verifyProof(pA, pB, pC, pubSignals);
      expect(result).to.be.true;
    });
  });
});
