"""
Poseidon hashing for TrustVerse credential commitments.

The backend needs to compute the exact same Poseidon hash that the
ClaimProver / NonRevocation / IssuerMembership circuits compute, or proofs
generated by the wallet will never match the credentialRoot anchored
on-chain. Rolling a second Poseidon implementation in Python is a common
source of off-by-one / parameter mismatches (rounds, S-box, MDS matrix), so
instead we shell out to a tiny Node sidecar (backend/poseidon_sidecar) that
uses circomlibjs - the same reference implementation circomlib's
poseidon.circom is built from.

Commitment layout (must match circuits/ClaimProver.circom and friends):

    claimsHash     = Poseidon(subjectId, cgpaScaled, degreeCode, issueDate)
    credentialRoot = Poseidon(claimsHash, issuerPubKey, salt, schemaId)
"""
import json
import os
import subprocess
from functools import lru_cache
from typing import List, Sequence

_SIDECAR_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "poseidon_sidecar")
_SIDECAR_DIR = os.path.abspath(_SIDECAR_DIR)
_SIDECAR_SCRIPT = os.path.join(_SIDECAR_DIR, "hash.js")


class PoseidonError(RuntimeError):
    pass


@lru_cache(maxsize=1)
def _node_binary() -> str:
    return os.getenv("NODE_BINARY", "node")


def poseidon_hash(inputs: Sequence[int]) -> int:
    """
    Compute the Poseidon hash of a list of field elements, returning a
    Python int (the field element, in [0, BN128 scalar field)).
    """
    if not inputs:
        raise PoseidonError("poseidon_hash requires at least one input")

    if not os.path.exists(_SIDECAR_SCRIPT):
        raise PoseidonError(
            f"Poseidon sidecar not found at {_SIDECAR_SCRIPT}. "
            "Run `npm install` in backend/poseidon_sidecar/."
        )

    payload = json.dumps([str(int(v)) for v in inputs])

    try:
        proc = subprocess.run(
            [_node_binary(), _SIDECAR_SCRIPT],
            input=payload,
            capture_output=True,
            text=True,
            timeout=30,
            cwd=_SIDECAR_DIR,
        )
    except FileNotFoundError as exc:
        raise PoseidonError(
            f"Could not execute node ('{_node_binary()}'). Is Node.js installed?"
        ) from exc
    except subprocess.TimeoutExpired as exc:
        raise PoseidonError("Poseidon sidecar timed out") from exc

    if proc.returncode != 0:
        raise PoseidonError(f"Poseidon sidecar failed: {proc.stderr.strip()}")

    try:
        result = json.loads(proc.stdout.strip())
        return int(result["hash"])
    except (json.JSONDecodeError, KeyError, ValueError) as exc:
        raise PoseidonError(
            f"Unexpected output from Poseidon sidecar: {proc.stdout!r}"
        ) from exc


def field_to_hex(value: int) -> str:
    """Render a field element as a 0x-prefixed, 32-byte hex string (bytes32)."""
    return "0x" + int(value).to_bytes(32, "big").hex()


def compute_claims_hash(subject_id: int, cgpa_scaled: int, degree_code: int, issue_date: int) -> int:
    """claimsHash = Poseidon(subjectId, cgpaScaled, degreeCode, issueDate)"""
    return poseidon_hash([subject_id, cgpa_scaled, degree_code, issue_date])


def compute_credential_root(claims_hash: int, issuer_pub_key: int, salt: int, schema_id: int) -> int:
    """credentialRoot = Poseidon(claimsHash, issuerPubKey, salt, schemaId)"""
    return poseidon_hash([claims_hash, issuer_pub_key, salt, schema_id])
